<?php
return [
    "HOME_PAGE" => "Home Page",
    "SETTINGS" => "Settings",
    "CATEGORIES" => "Categories",
    "SECTIONS" => "Sections",
    "COURSES" => "Courses",
    "USERS" => "Users",
    "ABOUT_US" => "About Us",
    "REQUESTS" => "Requests",
    "BLOG" => "Blog",
    "BLOG_TITLE" => "Blog",
    "CONTENT" => "Content",
    "MATERIALS" => "Materials",
    "MY_ACCOUNT" => "My Account",
    "ADMIN_PANEL" => "Admin Panel",
    "LOGOUT" => "Logout",
    "SITE_SLOGAN" => "Site Slogan",
    "SITE_NAME" => "Site Name",
    "SITE_LANG" => "Site Language",

    "CATEGORY" => "Category",
    "PARENT_ID" => "Parent",
    "CATEGORY_ID" => "Category",
    "PARENT_CATEGORY" => "Parent Category",
    "PRIMARY_CATEGORY" => "Primary Category",
    "CHOOSE_ONE" => "Choose One",

    "TITLE" => "Title",
    "ADD" => "Add",
    "START" => "Start",
    "SAVE" => "Save",
    "EDIT" => "Edit",
    "DELETE" => "Delete",
    "ACCOUNT_TYPE" => "Account Type",
    "STUDENT" => "Student",
    "ADMIN" => "Admin",
    "STATUS" => "Status",
    "ACTIVE" => "Active",
    "INACTIVE" => "Inactive",
    "BANNED" => "Banned",
    "OPTIONS" => "Options",

    "LOGIN" => "Login",
    "LOGIN_TITLE" => "Log-in to your account",

    "REGISTER" => "Sign Up",
    "REGISTER_TITLE" => "Create a new account",

    "HOME" => "Home",
    "HOME_TITLE" => "You are at home",

    "EMAIL" => "E-mail address",
    "PASSWORD" => "Password",
    "RETYPE_PASSWORD" => "Re-type Password",
    "NAME" => "Name",


    "SUBCATEGORIES" => "Subcategories",
    "SUBCATEGORIES_TITLE" => "Subcategories",
    "COURSES_TITLE" => "Courses",
    "MATERIAL" => "Material",
    "MATERIAL_TITLE" => "Material",
    "INSTRUCTOR" => "Instructor",
    "DATE" => "Date",


    "REGISTER_HINT" => "Have an account?",
    "LOGIN_HINT" => "New to us?",

    "EMAIL_OR_PASSWORD_WRONG" => "The Email or password is incorrect. Please try again.",
    "FILL_ALL_FIELDS" => "Please fill all fields then try again.",

    "FIELD_IS_REQUIRED" => "%s is required",

    "EMAIL_ALREADY_EXISTS" => "Email Is Already Exists",
    "PASSWORDS_NOT_MATCH" => "Passwords Don't Match",
    "EMAIL_NOT_VALID" => "Email address does not valid",


    "NO_ROWS" => "No data to display right now !",
    "ERROR_PAGE_TITLE" => "That’s an error",
    "ERROR_PAGE_DESC" => "The requested URL was not found on this server. That’s all we know.",
    "MESSAGE_TITLE" => "You have a message !!",
    "DELETE_CONFIRM_DESC" => "Are you sure you want to delete this? You can't undo this action.",
    "BACK" => "Back",

    "INTRODUCTION" => "Introduction",
    "DESCRIPTION" => "Description",
    "REQUIREMENT" => "Requirement",
    "AUDIENCE" => "Audience",
    "FEATURED_IMAGE" => "Feature Image",
    "UPLOAD_FILE" => "Upload File",
    "ADD_VIDEO" => "Add Video",
    "VIDEO_LINK" => "Video Link",
    "FILE" => "File",
    "LINK" => "Link",
    "LINK_NOT_SUPPORTED" => "The link you entered is not supported by %s",
    "UPLOAD_EMPTY" => "You must upload a file",
    "UPLOAD_EXCEEDS_SIZE" => "The file exceeds the maximum size allowed",
    "UPLOAD_CANT_USE_DIST" => "Unable to move the file to the specified target",
    "UPLOAD_TYPE_NOT_ALLOWED" => "Mime type is not allowed",
    "UPLOAD_MOVE_ERROR" => "Unable to move the file to the specified target",
];